/*
 * Copyright (c) 2016, Freescale Semiconductor, Inc.
 * Copyright 2016-2017 NXP
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.11.0 on Sun Aug 27 17:53:43 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_Caculator_h_)
#define _Caculator_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11100 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS_CACULATOR)
#define ERPC_TYPE_DEFINITIONS_CACULATOR

#endif // ERPC_TYPE_DEFINITIONS_CACULATOR

/*! @brief IMath identifiers */
enum _IMath_ids
{
    kIMath_service_id = 1,
    kIMath_add_id = 1,
};

/*! @brief ICounter identifiers */
enum _ICounter_ids
{
    kICounter_service_id = 2,
    kICounter_set_counter_id = 1,
    kICounter_get_counter_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name IMath
//@{
int32_t add(int32_t num_1, int32_t num_2);
//@}

//! @name ICounter
//@{
void set_counter(int32_t counter);

int32_t get_counter(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _Caculator_h_
